//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.17 at 03:12:01 PM EDT 
//


package gov.nist.scap.schema.cvss_v2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for authenticationEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="authenticationEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="MULTIPLE_INSTANCES"/>
 *     &lt;enumeration value="SINGLE_INSTANCE"/>
 *     &lt;enumeration value="NONE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "authenticationEnumType")
@XmlEnum
public enum AuthenticationEnumType {

    MULTIPLE_INSTANCES,
    SINGLE_INSTANCE,
    NONE;

    public String value() {
        return name();
    }

    public static AuthenticationEnumType fromValue(String v) {
        return valueOf(v);
    }

}
