//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.17 at 03:12:01 PM EDT 
//


package org.icasi.cvrf.schema.common;

import org.icasi.cvrf.schema.cvrf.Cvrfdoc;
import org.icasi.cvrf.schema.prod.ProductTree;
import org.icasi.cvrf.schema.vuln.Vulnerability;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * String type with an optional language attribute.  The default language is English.
 * 
 * <p>Java class for localizedString complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="localizedString">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.icasi.org/CVRF/schema/common/1.1>nonEmptyString">
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}lang default="en""/>
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "localizedString", propOrder = {
    "value"
})
@XmlSeeAlso({
    Cvrfdoc.DocumentPublisher.ContactDetails.class,
    Cvrfdoc.DocumentPublisher.IssuingAuthority.class,
    Cvrfdoc.DocumentTracking.Identification.ID.class,
    Cvrfdoc.DocumentTracking.Identification.Alias.class,
    Cvrfdoc.DocumentTracking.RevisionHistory.Revision.Description.class,
    Cvrfdoc.DocumentTracking.Generator.Engine.class,
    Cvrfdoc.DocumentNotes.Note.class,
    Cvrfdoc.DocumentDistribution.class,
    Cvrfdoc.AggregateSeverity.class,
    Cvrfdoc.DocumentReferences.Reference.Description.class,
    Cvrfdoc.Acknowledgments.Acknowledgment.Name.class,
    Cvrfdoc.Acknowledgments.Acknowledgment.Organization.class,
    Cvrfdoc.Acknowledgments.Acknowledgment.Description.class,
    ProductTree.ProductGroups.Group.Description.class,
    Vulnerability.Title.class,
    Vulnerability.Notes.Note.class,
    Vulnerability.Involvements.Involvement.Description.class,
    Vulnerability.CWE.class,
    Vulnerability.Threats.Threat.Description.class,
    Vulnerability.Remediations.Remediation.Description.class,
    Vulnerability.Remediations.Remediation.Entitlement.class,
    Vulnerability.References.Reference.Description.class,
    Vulnerability.Acknowledgments.Acknowledgment.Name.class,
    Vulnerability.Acknowledgments.Acknowledgment.Organization.class,
    Vulnerability.Acknowledgments.Acknowledgment.Description.class
})
public class LocalizedString {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    protected String lang;

    /**
     * A string type that cannot be empty.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Locale code used for the string value.  The default is "en".
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        if (lang == null) {
            return "en";
        } else {
            return lang;
        }
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

}
